before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

snapcrafts:
  - title: httpmock-netlogger
    publish: true
    summary: "A simple HTTP Server mock which log every network connections events"
    description: "A simple HTTP Server mock which log every network connections events"
    license: MIT

    apps:
      httpmock-netlogger:
        plugs: ["network-bind"]

dockers:
  - image_templates:
      - "ghcr.io/emmanuelgautier/httpmock-netlogger:{{ .Tag }}"
      - "ghcr.io/emmanuelgautier/httpmock-netlogger:v{{ .Major }}"
      - "ghcr.io/emmanuelgautier/httpmock-netlogger:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/emmanuelgautier/httpmock-netlogger:latest"
    dockerfile: .docker/Dockerfile-goreleaser
