FROM golang:1.23-bullseye AS builder

WORKDIR /go/src/github.com/emmanuelgautier/httpmock-netlogger

COPY go.mod go.mod
COPY go.sum go.sum

ENV CGO_ENABLED 0
ENV GO111MODULE on

RUN go mod download

COPY . .

RUN go build -o /usr/bin/httpmock-netlogger .

FROM gcr.io/distroless/static-debian11:nonroot AS runner

COPY --from=builder --chown=nonroot:nonroot /usr/bin/httpmock-netlogger /usr/bin/httpmock-netlogger

ENTRYPOINT ["httpmock-netlogger", "serve"]
CMD ["httpmock-netlogger"]
